import { supabase } from "@/integrations/supabase/client";

/**
 * Call a canonical RPC that exists in supabase/migrations but is not yet in the
 * generated `Database` type.
 *
 * TEMPORARY — DELETE THIS FILE once types are regenerated.
 *
 * `src/integrations/supabase/types.ts` is generated by `supabase gen types`
 * against a replayed migration chain, which needs Docker. Until that runs, the
 * Mentoring canonical functions added by 20260921110000 / 20260921120000 have
 * no generated signature, so `supabase.rpc("book_mentoring_session", …)` does
 * not typecheck.
 *
 * The alternative — hand-writing the missing entries into the generated file —
 * is worse: it puts definitions nobody generated into a file everyone assumes
 * is machine-produced, and the next regeneration silently overwrites them, so
 * a drift between the declared and the real signature would never be caught.
 *
 * This casts once, at the single boundary where the gap exists, and names the
 * argument and return shapes locally so call sites stay typed. Every function
 * listed in PENDING_RPCS must exist in a committed migration.
 *
 * When types are regenerated: replace these calls with `supabase.rpc(...)`
 * directly and delete this module. The guard in
 * src/test/programmeProfileArchitecture.test.ts fails if a name listed here
 * has no migration defining it.
 */
export const PENDING_RPCS = [
  "book_mentoring_session",
  "transition_mentoring_session_status",
  "update_mentoring_session_notes",
  "mentoring_session_evidence",
  "canonical_mentoring_requirement_fulfilment",
  "next_mentoring_requirement",
] as const;

export type PendingRpc = (typeof PENDING_RPCS)[number];

/**
 * Same result shape as `supabase.rpc`, so call sites handle `error` exactly as
 * they do for a generated RPC — this changes typing only, never behaviour.
 */
export async function callPendingRpc<TResult>(
  fn: PendingRpc,
  args: Record<string, unknown>,
): Promise<{ data: TResult | null; error: { message: string; code?: string } | null }> {
  const client = supabase as unknown as {
    rpc: (
      name: string,
      params: Record<string, unknown>,
    ) => Promise<{ data: unknown; error: { message: string; code?: string } | null }>;
  };
  const { data, error } = await client.rpc(fn, args);
  return { data: (data as TResult) ?? null, error };
}
