project_id = "ygufjhhpguauwwmfvczy"

[functions]
  [functions.approve-access-request]
    verify_jwt = true
  [functions.confirm-session]
    verify_jwt = true
  [functions.confirm-mentoring-session]
    verify_jwt = true
  [functions.send-mentoring-prep-file]
    verify_jwt = true
  [functions.send-mentoring-feedback]
    verify_jwt = true
  [functions.cancel-session]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.seed-demo-data]
    verify_jwt = true
  [functions.invite-sponsor]
    verify_jwt = true
  [functions.coach-invite-coachee]
    verify_jwt = true
  [functions.admin-bulk-invite-users]
    verify_jwt = true
