// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/approve-access-request.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseServiceRoleKey() {
  return configuredEnv(["SUPABASE_SERVICE_ROLE_KEY"]);
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseAdmin() {
  const key = supabaseServiceRoleKey();
  if (!key) throw new Error("SUPABASE_SERVICE_ROLE_KEY is required");
  return createClient(supabaseProjectUrl(), key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/utils.ts
var ROLE_PRIORITY = { admin: 1, coach: 2, coachee: 3 };
async function getUserRole(userId) {
  const { data, error } = await supabaseAdmin().from("user_roles").select("role").eq("user_id", userId);
  if (error || !data || data.length === 0) return null;
  const roles = data.map((r) => r.role);
  return roles.sort((a, b) => ROLE_PRIORITY[a] - ROLE_PRIORITY[b])[0];
}
function generatePassword() {
  const lowers = "abcdefghijkmnpqrstuvwxyz";
  const uppers = "ABCDEFGHJKLMNPQRSTUVWXYZ";
  const digits = "23456789";
  const symbols = "!@#$%&*";
  const all = lowers + uppers + digits + symbols;
  const buf = new Uint8Array(14);
  crypto.getRandomValues(buf);
  const pick = (set, byte) => set[byte % set.length];
  const chars = [
    pick(lowers, buf[0]),
    pick(uppers, buf[1]),
    pick(digits, buf[2]),
    pick(symbols, buf[3]),
    ...Array.from(buf.slice(4)).map((b) => pick(all, b))
  ];
  for (let i = chars.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [chars[i], chars[j]] = [chars[j], chars[i]];
  }
  return chars.join("");
}

// src/lib/mcp/tools/approve-access-request.ts
var approve_access_request_default = defineTool({
  name: "approve_access_request",
  title: "Approve access request",
  description: "Approve a pending access request, create the user account, and return a one-time temporary password.",
  inputSchema: {
    request_id: z.string().uuid().describe("UUID of the pending access request")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ request_id }, ctx) => {
    const callerId = ctx.getUserId();
    if (!callerId) throw new ToolError("Not authenticated");
    const role = await getUserRole(callerId);
    if (role !== "admin") throw new ToolError("Admin access required");
    const admin = supabaseAdmin();
    const { data: reqRow, error: reqErr } = await admin.from("access_requests").select("*").eq("id", request_id).maybeSingle();
    if (reqErr || !reqRow) throw new ToolError(reqErr?.message ?? "Request not found");
    if (reqRow.status === "approved") throw new ToolError("Request already approved");
    const userRole = reqRow.role === "coach" ? "coach" : "coachee";
    const tempPassword = generatePassword();
    let userId = null;
    const { data: existingProfile } = await admin.from("profiles").select("id").ilike("email", reqRow.email).maybeSingle();
    if (existingProfile?.id) {
      userId = existingProfile.id;
      const { error: updateUserErr } = await admin.auth.admin.updateUserById(userId, {
        password: tempPassword,
        email_confirm: true,
        user_metadata: { full_name: reqRow.full_name, role: userRole }
      });
      if (updateUserErr) throw new ToolError(updateUserErr.message ?? "Failed to update existing user");
    } else {
      const { data: created, error: createErr } = await admin.auth.admin.createUser({
        email: reqRow.email,
        password: tempPassword,
        email_confirm: true,
        user_metadata: { full_name: reqRow.full_name, role: userRole }
      });
      if (createErr || !created.user) throw new ToolError(createErr?.message ?? "Failed to create user");
      userId = created.user.id;
    }
    if (!userId) throw new ToolError("Could not resolve user account");
    await admin.from("profiles").update({ status: "active", must_change_password: true }).eq("id", userId);
    if (userRole === "coach") {
      await admin.from("coach_profiles").update({ approval_status: "active", last_approved_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", userId);
    } else {
      await admin.from("coachee_profiles").update({ approval_status: "active", last_approved_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", userId);
    }
    await admin.from("access_requests").update({ status: "approved", reviewed_at: (/* @__PURE__ */ new Date()).toISOString(), reviewed_by: callerId }).eq("id", request_id);
    return {
      content: [{ type: "text", text: `Approved. Email: ${reqRow.email}
Temporary password: ${tempPassword}
Role: ${userRole}` }],
      structuredContent: { email: reqRow.email, temp_password: tempPassword, role: userRole, user_id: userId }
    };
  }
});

// src/lib/mcp/tools/get-coach-profile.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_coach_profile_default = defineTool2({
  name: "get_coach_profile",
  title: "Get coach profile",
  description: "Get the full profile for a coach.",
  inputSchema: {
    coach_id: z2.string().uuid().describe("UUID of the coach")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ coach_id }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(`
        id, full_name, email, bio, avatar_url, status, created_at,
        coach_profiles(title, specialties, diplomas_certifications, years_experience, hourly_rate, rating_avg, sessions_completed, country_based, nationality, calendly_url, peer_coaching_opt_in)
      `).eq("id", coach_id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2("Coach not found or access denied");
    return { content: [{ type: "text", text: JSON.stringify(data) }] };
  }
});

// src/lib/mcp/tools/get-coachee-profile.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_coachee_profile_default = defineTool3({
  name: "get_coachee_profile",
  title: "Get coachee profile",
  description: "Get the full profile for a coachee, including programme enrollment and limits.",
  inputSchema: {
    coachee_id: z3.string().uuid().describe("UUID of the coachee")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ coachee_id }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError3("Not authenticated");
    const role = await getUserRole(userId);
    if (!role) throw new ToolError3("Role not found");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(`
        id, full_name, email, bio, avatar_url, status, created_at,
        coachee_profiles(industry, job_title, location, phone, timezone, goals),
        programme_enrollments(id, start_date, end_date, status, progress_pct, programmes(name, duration_months, coachee_session_limit, peer_session_limit, peer_given_limit)),
        session_limits(monthly_limit)
      `).eq("id", coachee_id).maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!data) throw new ToolError3("Coachee not found or access denied");
    return { content: [{ type: "text", text: JSON.stringify(data) }] };
  }
});

// src/lib/mcp/tools/get-coachee-progress.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var get_coachee_progress_default = defineTool4({
  name: "get_coachee_progress",
  title: "Get coachee progress",
  description: "Get a coachee's programme progress, session counts, and average goal ratings.",
  inputSchema: {
    coachee_id: z4.string().uuid().describe("UUID of the coachee")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ coachee_id }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError4("Not authenticated");
    const role = await getUserRole(userId);
    if (!role) throw new ToolError4("Role not found");
    if (role === "coachee" && userId !== coachee_id) throw new ToolError4("You can only view your own progress");
    const supabase = supabaseForUser(ctx);
    const [{ data: enrollment }, { data: sessions }, { data: ratings }] = await Promise.all([
      supabase.from("programme_enrollments").select("id, start_date, end_date, progress_pct, status, programmes(name, duration_months, coachee_session_limit)").eq("coachee_id", coachee_id).maybeSingle(),
      supabase.from("sessions").select("status", { count: "exact" }).eq("coachee_id", coachee_id),
      supabase.from("coachee_goal_ratings").select("start_rating, current_rating, target_rating").eq("coachee_id", coachee_id)
    ]);
    const completed = sessions?.filter((s) => s.status === "completed").length ?? 0;
    const avgCurrent = ratings && ratings.length > 0 ? ratings.reduce((sum, r) => sum + r.current_rating, 0) / ratings.length : null;
    const avgTarget = ratings && ratings.length > 0 ? ratings.reduce((sum, r) => sum + r.target_rating, 0) / ratings.length : null;
    return {
      content: [{
        type: "text",
        text: JSON.stringify({
          enrollment,
          session_counts: { total: sessions?.length ?? 0, completed },
          goal_averages: { current: avgCurrent, target: avgTarget, goal_count: ratings?.length ?? 0 }
        })
      }]
    };
  }
});

// src/lib/mcp/tools/get-session-details.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var get_session_details_default = defineTool5({
  name: "get_session_details",
  title: "Get session details",
  description: "Get full details for a coaching session, including notes and goal ratings.",
  inputSchema: {
    session_id: z5.string().uuid().describe("UUID of the session")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError5("Not authenticated");
    const role = await getUserRole(userId);
    if (!role) throw new ToolError5("Role not found");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("sessions").select(`
        id, topic, start_time, duration_minutes, status, meeting_url, action_items,
        coach_notes, coachee_notes, coachee_rating, coachee_rating_comment,
        coach:coach_id(id, full_name),
        coachee:coachee_id(id, full_name),
        session_goal_ratings(id, goal_id, rating, note, created_at, coachee_goals(title))
      `).eq("id", session_id).maybeSingle();
    if (error) throw new ToolError5(error.message);
    if (!data) throw new ToolError5("Session not found or access denied");
    return { content: [{ type: "text", text: JSON.stringify(data) }] };
  }
});

// src/lib/mcp/tools/list-coaches.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var list_coaches_default = defineTool6({
  name: "list_coaches",
  title: "List coaches",
  description: "List all active coaches in the directory.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).default(50).describe("Maximum number of coaches to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(`
        id, full_name, email, avatar_url, status,
        coach_profiles(title, specialties, years_experience, hourly_rate, rating_avg, sessions_completed, country_based, approval_status)
      `).eq("coach_profiles.approval_status", "active").order("full_name").limit(limit);
    if (error) throw new ToolError6(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/list-coachee-goals.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var list_coachee_goals_default = defineTool7({
  name: "list_coachee_goals",
  title: "List coachee goals",
  description: "List goals and current ratings for a coachee.",
  inputSchema: {
    coachee_id: z7.string().uuid().describe("UUID of the coachee")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ coachee_id }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError7("Not authenticated");
    const role = await getUserRole(userId);
    if (!role) throw new ToolError7("Role not found");
    if (role === "coachee" && userId !== coachee_id) throw new ToolError7("You can only view your own goals");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("coachee_goals").select(`
        id, title, description, status, target_date, sort_order, created_at,
        coachee_goal_ratings(start_rating, current_rating, target_rating)
      `).eq("coachee_id", coachee_id).order("sort_order");
    if (error) throw new ToolError7(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/list-coachees.ts
import { defineTool as defineTool8, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^4.4.3";
var list_coachees_default = defineTool8({
  name: "list_coachees",
  title: "List coachees",
  description: "List coachees visible to the signed-in user (all for admins, assigned coachees for coaches).",
  inputSchema: {
    limit: z8.number().int().min(1).max(100).default(50).describe("Maximum number of coachees to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError8("Not authenticated");
    const role = await getUserRole(userId);
    if (!role || role === "coachee") throw new ToolError8("Admin or coach access required");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("profiles").select("id, full_name, email, status, created_at, coachee_profiles!inner(industry, job_title, location)").eq("coachee_profiles.id", "id").order("full_name").limit(limit);
    if (role === "coach") {
      query = query.eq("sessions.coach_id", userId);
    }
    const { data, error } = await query;
    if (error) throw new ToolError8(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/list-pending-access-requests.ts
import { defineTool as defineTool9, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_pending_access_requests_default = defineTool9({
  name: "list_pending_access_requests",
  title: "List pending access requests",
  description: "List all access requests awaiting admin approval.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError9("Not authenticated");
    const role = await getUserRole(userId);
    if (role !== "admin") throw new ToolError9("Admin access required");
    const { data, error } = await supabaseAdmin().from("access_requests").select("id, full_name, email, role, company, job_title, industry, motivation, created_at, status").eq("status", "pending").order("created_at", { ascending: false });
    if (error) throw new ToolError9(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/list-programmes.ts
import { defineTool as defineTool10, ToolError as ToolError10 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_programmes_default = defineTool10({
  name: "list_programmes",
  title: "List programmes",
  description: "List active coaching programmes and their session limits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError10("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("programmes").select("id, name, description, duration_months, coachee_session_limit, coach_session_limit, peer_session_limit, peer_given_limit, color, is_active").eq("is_active", true).order("name");
    if (error) throw new ToolError10(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool11, ToolError as ToolError11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^4.4.3";
var list_sessions_default = defineTool11({
  name: "list_sessions",
  title: "List sessions",
  description: "List coaching sessions visible to the signed-in user.",
  inputSchema: {
    status: z9.enum(["pending", "confirmed", "completed", "cancelled"]).optional().describe("Filter by session status"),
    limit: z9.number().int().min(1).max(100).default(50).describe("Maximum number of sessions to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError11("Not authenticated");
    const role = await getUserRole(userId);
    if (!role) throw new ToolError11("Role not found");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("sessions").select(`
        id, topic, start_time, duration_minutes, status, confirmed_at, cancelled_at,
        coach:coach_id(full_name),
        coachee:coachee_id(full_name)
      `).order("start_time", { ascending: false }).limit(limit);
    if (role === "admin") {
    } else if (role === "coach") {
      query = query.or(`coach_id.eq.${userId}`);
    } else {
      query = query.eq("coachee_id", userId);
    }
    if (status) {
      query = query.eq("status", status);
    }
    const { data, error } = await query;
    if (error) throw new ToolError11(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/tools/reject-access-request.ts
import { defineTool as defineTool12, ToolError as ToolError12 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^4.4.3";
var reject_access_request_default = defineTool12({
  name: "reject_access_request",
  title: "Reject access request",
  description: "Reject a pending access request.",
  inputSchema: {
    request_id: z10.string().uuid().describe("UUID of the pending access request")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ request_id }, ctx) => {
    const callerId = ctx.getUserId();
    if (!callerId) throw new ToolError12("Not authenticated");
    const role = await getUserRole(callerId);
    if (role !== "admin") throw new ToolError12("Admin access required");
    const admin = supabaseAdmin();
    const { data: reqRow, error: reqErr } = await admin.from("access_requests").select("status").eq("id", request_id).maybeSingle();
    if (reqErr || !reqRow) throw new ToolError12(reqErr?.message ?? "Request not found");
    if (reqRow.status !== "pending") throw new ToolError12("Request is not pending");
    const { error } = await admin.from("access_requests").update({ status: "rejected", reviewed_at: (/* @__PURE__ */ new Date()).toISOString(), reviewed_by: callerId }).eq("id", request_id);
    if (error) throw new ToolError12(error.message);
    return { content: [{ type: "text", text: "Access request rejected." }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fgzhdyeneycdzitbimhk";
var mcp_default = defineMcp({
  name: "clariva-club",
  title: "Clariva Club",
  version: "0.1.0",
  instructions: "Tools for Clariva Club executive coaching platform. Admins can approve access requests and view all people and sessions. Coaches can view their assigned coachees, sessions, and coach directory. Coachees can view their own profile, goals, progress, and sessions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_pending_access_requests_default,
    approve_access_request_default,
    reject_access_request_default,
    list_coachees_default,
    get_coachee_profile_default,
    list_coaches_default,
    get_coach_profile_default,
    list_programmes_default,
    list_sessions_default,
    get_session_details_default,
    list_coachee_goals_default,
    get_coachee_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
