-- Retired demo seed.
--
-- Programme demo data is intentionally not created by migrations.  The
-- replacement is supabase/functions/seed-demo-data and is guarded by
-- APP_ENV/ENVIRONMENT (local, development, preview, or test).  Keeping this
-- migration as a no-op means a production reset can never create demo auth
-- identities, overwrite credentials, or perform a destructive cleanup.
--
-- Use the guarded seed function after a local reset:
--   supabase functions serve seed-demo-data
--   curl -X POST .../functions/v1/seed-demo-data
--
-- Fixed timeline anchor: 2026-01-05. Programme A ends 2026-04-05;
-- Programme B ends 2026-07-05. Re-running upserts the same programme,
-- cohort, profile, and sponsor records and uses
-- admin_create_programme_enrollment (which generates schedules).